// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWw8wmQAkZTpOd4_vmA4rrQsxlY1OIniU',
    appId: '1:512961380350:web:961ab27b04b67c42b28aaf',
    messagingSenderId: '512961380350',
    projectId: 'nss---national-service-scheme',
    authDomain: 'nss---national-service-scheme.firebaseapp.com',
    storageBucket: 'nss---national-service-scheme.firebasestorage.app',
    measurementId: 'G-WYLLW1S7V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNg6bec70ij7ZHtPZrZLB0DL9z_uXpE_4',
    appId: '1:512961380350:android:dbc59a93ff4af81bb28aaf',
    messagingSenderId: '512961380350',
    projectId: 'nss---national-service-scheme',
    storageBucket: 'nss---national-service-scheme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAftT20elJxaSpzl635ydQI6iFrcKoZX3Y',
    appId: '1:512961380350:ios:4959136aab68807db28aaf',
    messagingSenderId: '512961380350',
    projectId: 'nss---national-service-scheme',
    storageBucket: 'nss---national-service-scheme.firebasestorage.app',
    iosBundleId: 'com.example.nssApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAftT20elJxaSpzl635ydQI6iFrcKoZX3Y',
    appId: '1:512961380350:ios:4959136aab68807db28aaf',
    messagingSenderId: '512961380350',
    projectId: 'nss---national-service-scheme',
    storageBucket: 'nss---national-service-scheme.firebasestorage.app',
    iosBundleId: 'com.example.nssApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWw8wmQAkZTpOd4_vmA4rrQsxlY1OIniU',
    appId: '1:512961380350:web:29f5ed71106ad128b28aaf',
    messagingSenderId: '512961380350',
    projectId: 'nss---national-service-scheme',
    authDomain: 'nss---national-service-scheme.firebaseapp.com',
    storageBucket: 'nss---national-service-scheme.firebasestorage.app',
    measurementId: 'G-7J2JWJRPC2',
  );
}
